use super::schools::SchoolState;
use super::shop::PurchaseTracker;
use bevy::prelude::*;

#[derive(Resource, Debug)]
pub struct WisdomMeter {
    pub current: f32,
    pub max_wisdom: f32,
    pub truths_generated: u32,
}

impl Default for WisdomMeter {
    fn default() -> Self {
        Self {
            current: 0.0,
            max_wisdom: 10.0,
            truths_generated: 0,
        }
    }
}

#[derive(Message)]
pub struct TruthGenerated {
    pub text: String,
}

const DEEP_TRUTHS: &[&str] = &[
    // Original truths
    "The orb knows what the clock forgets.",
    "Silence has a color, but only on Tuesdays.",
    "Every circle is a line that got homesick.",
    "The void stares back, but only to check if you brought snacks.",
    "Wisdom is just ignorance with better lighting.",
    "The universe expanded, then immediately regretted it.",
    "Time flows like honey through a philosopher's beard.",
    "All paths lead somewhere, but most require comfortable shoes.",
    "The deepest truth is that there is no spoon, but there is a ladle.",
    "Stars are just the night sky's freckles.",
    "Knowledge grows in the dark, like mushrooms and suspicion.",
    "The orb does not judge. The orb simply... orbs.",
    "Contemplation is just staring with better PR.",
    "The moon is the sun's cover band.",
    "Entropy is just the universe getting comfortable.",
    "If a tree falls in a forest and no wizard ponders it, was it ever truly a tree?",
    "The shadow of the mountain does not fear the sun.",
    "Even a square is just a circle that has lost its way.",
    // Cosmic musings
    "Gravity is just the universe's way of hugging.",
    "Black holes are where the universe keeps its drafts.",
    "Light travels fast because it has nothing to pack.",
    "The cosmos is mostly empty, much like a philosopher's refrigerator.",
    "Nebulae are just clouds that got above themselves.",
    "Dark matter is just matter that values its privacy.",
    "A supernova is a star's way of leaving the conversation dramatically.",
    "The speed of light is the universe's upload limit.",
    "Comets are just ice cubes the cosmos forgot about.",
    "Galaxies spiral because straight lines are boring at that scale.",
    "The Big Bang was the universe's alarm clock, and it's been hitting snooze ever since.",
    "Asteroids are just rocks with ambition and poor navigation.",
    "Saturn's rings are the cosmos's way of accessorizing.",
    "A quasar is a lighthouse for ships that will never sail.",
    "Pulsars are the universe's metronome, keeping time for no one.",
    "The cosmic microwave background is the universe's baby photo.",
    "Neutron stars spin because standing still is for amateurs.",
    "The Milky Way is named after something it will never taste.",
    "Solar flares are the sun throwing a tantrum.",
    "The vacuum of space is full of things pretending not to be there.",
    "Orbits are just falling with style and commitment.",
    "The universe doesn't owe you an explanation, but it left clues anyway.",
    "Red dwarfs burn slowly because they read the instructions first.",
    "Planetary rings are just cosmic hula hoops that never came down.",
    // Orb philosophy
    "To ponder the orb is to let the orb ponder you.",
    "The orb remembers every thought you almost had.",
    "An unpondered orb is just a fancy marble.",
    "The orb's glow is fueled by the audacity of contemplation.",
    "Some say the orb dreams. The orb says dreams are just orbs you haven't met.",
    "The orb does not answer questions. It makes you forget you had them.",
    "Within every orb is a smaller orb, and so on, forever.",
    "The orb was here before the table. The table simply appeared out of politeness.",
    "You do not choose to ponder the orb. The orb allows you to think you did.",
    "The orb has seen the void, and the void blinked first.",
    "The orb does not glow. It simply stops hiding its light.",
    "Every orb contains a universe that contains an orb.",
    "The orb forgives your distractions. It was pondering them too.",
    "One does not simply look at the orb. One is looked at by it.",
    "The orb's silence speaks volumes, but only in languages yet to be invented.",
    "If you listen carefully, the orb hums a song it hasn't learned yet.",
    "The orb casts no shadow, for the shadow refused to participate.",
    "The orb once pondered itself. The resulting paradox is still settling.",
    "All orbs are one orb, experiencing itself from different angles.",
    "The orb's favorite color is a feeling.",
    "The orb is patient because it has already seen how this ends.",
    "When the orb is still, it is actually moving through dimensions you can't perceive.",
    "The orb does not float. The ground simply respects its boundaries.",
    "To truly know the orb, you must first forget everything, including this advice.",
    "The orb appreciates your pondering, but asks that you not overthink it.",
    "The orb is neither full nor empty. It is orb.",
    // Arcane observations
    "Magic is just science that hasn't been caught yet.",
    "A wand is a stick that went to university.",
    "Runes are just tattoos for rocks.",
    "Alchemy is cooking with more dramatic failures.",
    "Every spell is just a strongly-worded letter to reality.",
    "Enchantment is just flattery that works on objects.",
    "A grimoire is a cookbook for people who hate dinner parties.",
    "Mana is just coffee for the metaphysically inclined.",
    "Teleportation is walking with better time management.",
    "Divination is just reading spoilers for your own life.",
    "Potions are just tea for people who can't let go of the dramatic.",
    "A familiar is a pet that filed the right paperwork.",
    "Hexes are just curses with a brand identity.",
    "Scrolls are just spells that prefer the written word.",
    "Summoning circles are just doorbells for other dimensions.",
    "Invisibility is just introversion taken to its logical conclusion.",
    "Necromancy is just networking with a longer contact list.",
    "A crystal ball is an orb that went into consulting.",
    "Fireballs are just aggressively extroverted candles.",
    "Levitation is just jumping without the landing.",
    "Illusion magic is just arts and crafts for the impatient.",
    "A staff is just a wand that takes itself too seriously.",
    "Transmutation is just arts and crafts at the molecular level.",
    "A ward is a polite no-trespassing sign for the ethereal.",
    "Conjuration is just online shopping with faster delivery.",
    // Existential wisdom
    "Existence is a group project and nobody read the brief.",
    "The meaning of life is a trick question written by a committee.",
    "Free will is a multiple choice test with no wrong answers and no right ones.",
    "Reality is just a rumor that most particles agree on.",
    "Consciousness is the universe trying to see itself in a mirror.",
    "Infinity is just one, but it forgot when to stop.",
    "Nothing is impossible, but Nothing is also very lazy.",
    "The present is a gift, which is why it's so hard to return.",
    "Yesterday is just today's unreliable narrator.",
    "Tomorrow is today's fanfiction.",
    "You are the universe experiencing itself, and the universe didn't study for this.",
    "Every atom in your body was once part of a star that also had no idea what it was doing.",
    "Purpose is a direction, not a destination. Also, the map is upside down.",
    "Identity is a ship of Theseus, and the planks are arguing.",
    "Perception is reality's rough draft.",
    "The self is a story the brain tells to avoid an existential crisis.",
    "Fate and coincidence are the same thing wearing different hats.",
    "Choice is an illusion, but it's a very convincing one, so enjoy it.",
    "Being is easy. Becoming is the hard part.",
    "The universe is under no obligation to make sense to you. It barely makes sense to itself.",
    "Your thoughts are just neurons gossiping.",
    "Certainty is just doubt that stopped asking questions.",
    "Absurdity is the only honest response to an absurd universe.",
    // Acolyte wisdom
    "An acolyte does not ponder faster. They ponder wider.",
    "To summon is to politely inconvenience the astral plane.",
    "The first acolyte wonders why. The tenth just vibes.",
    "Acolytes do not sleep. They enter a state of horizontal pondering.",
    "A master is just an acolyte who ran out of questions.",
    "The difference between a sage and a fool is mostly hat quality.",
    "An acolyte's first lesson: the orb is always watching. The second lesson: that's fine.",
    "Acolytes collect wisdom like squirrels collect acorns. Most of it is forgotten by spring.",
    "The robe does not make the acolyte, but it does improve the silhouette.",
    "Acolytes speak in riddles because straight answers are exhausting.",
    "A senior acolyte is just someone who has forgotten more truths than a novice has learned.",
    "The acolyte's path is long, winding, and occasionally uphill both ways.",
    "An acolyte measures progress in epiphanies, not steps.",
    "When two acolytes disagree, the orb is amused. When they agree, the orb is suspicious.",
    "The initiation ritual is just making tea, but with more candles.",
    "Acolytes do not graduate. They simply stop being surprised.",
    // Nature and elements
    "Rain is the sky returning books it borrowed from the ocean.",
    "Mountains are the earth's way of trying to touch the sky.",
    "Rivers never make the same mistake twice. They just find new ones.",
    "Fog is the atmosphere being indecisive.",
    "Lightning is the sky's way of taking flash photography.",
    "Volcanoes are just mountains having a bad day.",
    "Deserts are beaches that lost their ocean.",
    "Caves are just rooms that forgot to install windows.",
    "Snow is just rain that overdressed for the occasion.",
    "Earthquakes are the planet stretching after a long nap.",
    "Tides are the moon's way of petting the Earth.",
    "Coral reefs are cities built by creatures with infinite patience and no zoning laws.",
    "A forest is just a very slow crowd.",
    "Glaciers are rivers that believe in taking their time.",
    "Thunder is just lightning's press release.",
    "Waterfalls are rivers that chose drama over efficiency.",
    "Mushrooms are the forest's way of composting with flair.",
    "The wind has never been seen, only felt. It's the ultimate introvert.",
    "Crystals are just minerals that got their life together.",
    "Moss grows on everything because it has no concept of personal space.",
    "An island is just a mountain that's mostly underwater and very private about it.",
    "Rainbows are just light showing off after a storm.",
    "Geysers are just the earth sneezing.",
    "Amber is tree sap that learned the value of patience.",
    // Time and patience
    "Patience is just procrastination with a better reputation.",
    "A watched pot never boils, but an unwatched one floods the kitchen.",
    "Eternity is a long time, especially towards the end.",
    "The best time to start pondering was yesterday. The second best time is now.",
    "Clocks don't measure time. They just make it feel guilty.",
    "A moment lasts forever if you forget to let go of it.",
    "Time heals all wounds, but it's a terrible surgeon.",
    "The past is a foreign country. They do things differently there, and the exchange rate is awful.",
    "A deadline is just a suggestion that reality keeps ignoring.",
    "Waiting is just being early to something that hasn't happened yet.",
    "Nostalgia is just the past wearing rose-tinted glasses and asking for a second date.",
    "Calendars are just planners for people who trust the future.",
    "A century is just a really long weekend for a mountain.",
    "Dusk is just dawn's evening wear.",
    "The future is just the past that hasn't made its mistakes yet.",
    "An hourglass is just sand going for a very slow walk.",
    "History repeats itself because nobody takes notes.",
    // Food for thought
    "Bread rises because it believes in itself.",
    "A sandwich is just a hug for ingredients.",
    "Tea is just hot leaf water that achieved enlightenment.",
    "The pretzel understands the nature of the knot better than any sailor.",
    "Soup is a potion that gave up on ambition.",
    "Cheese is just milk with commitment issues.",
    "A cake is just bread that went to a party.",
    "Spices are just plants that refused to be boring.",
    "Coffee is a hug from the inside, administered by a bean.",
    "Fermentation is just food taking a gap year.",
    "A salad is just a garden that got too close to a plate.",
    "Honey is just flower nectar that was processed by committee.",
    "An egg is potential wrapped in calcium.",
    "Butter is just cream that had a breakdown.",
    "Pasta is flour and water that found purpose through boiling.",
    "Chocolate is proof that the universe wants us to be happy, occasionally.",
    "A stew is just a soup that committed to the bit.",
    "Sourdough is bread that took a gap century.",
    "Ice cream is just frozen milk pretending to be a celebration.",
    "An onion has layers because it has trust issues.",
    // Deep nonsense
    "If you stare into the abyss long enough, it starts charging rent.",
    "The pen is mightier than the sword, but the eraser outranks them both.",
    "A door is just a wall that couldn't commit.",
    "Stairs are just floors that couldn't agree on a height.",
    "Glass is a liquid pretending to be a solid. Trust nothing.",
    "Maps are just drawings that people take too seriously.",
    "A mirror shows you backwards, yet nobody files a complaint.",
    "Shadows are just darkness that learned to follow instructions.",
    "Echoes are just sounds that enjoy their own company.",
    "Dust is just confetti for people who don't like parties.",
    "A bridge is just a road that got over it.",
    "Keys are just tiny swords for very small doors.",
    "A fence is just a wall going through a phase.",
    "Wheels are just circles that got a job.",
    "Candles are just torches with imposter syndrome.",
    "A hat is just a roof for your head.",
    "Bricks are just rocks with a strong work ethic.",
    "A compass doesn't know where you're going. It only knows where north went.",
    "Paint is just colored regret until it dries.",
    "A boat is just a car that failed geography.",
    "Pockets are just tiny rooms in your clothes.",
    "A pillow is a cloud that gave up on floating.",
    "Shoes are just leather boxes for your feet, and everyone acts like that's normal.",
    "An umbrella is just a tiny roof you carry around in case of sky water.",
    // Philosophical musings
    "The question is not why, but why not. And also how. And when. And lunch.",
    "Overthinking is just thinking that forgot to stop.",
    "A paradox is just logic having an identity crisis.",
    "Simplicity is complexity that has been resolved.",
    "An opinion is just a fact that hasn't been checked.",
    "Debate is just arguing with better posture.",
    "Logic is just feelings wearing a lab coat.",
    "A theory is just a guess that went to graduate school.",
    "Common sense is neither common nor a sense. Discuss.",
    "A conclusion is just the place where you got tired of thinking.",
    "Skepticism is just curiosity with its arms crossed.",
    "Wisdom comes with age, but sometimes age comes alone.",
    "An assumption is a truth that skipped the verification step.",
    "Irony is the universe's favorite rhetorical device.",
    "A cliché is just a truth that got overplayed.",
    // Tower and sanctum observations
    "The tower stands not because it must, but because sitting was never an option.",
    "Each step of the tower is a choice. The landing is the consequence.",
    "The view from the top is the same sky, just with more stairs behind you.",
    "Candles in a tower burn not to light the way, but to prove darkness has limits.",
    "The tower has no roof because even stone knows when to stop.",
    "A sanctum is just a room that takes itself seriously.",
    "The flicker of a candle is the only honest conversation in the room.",
    "Stone walls keep nothing out. They only decide what stays in.",
    "A tower without stairs is just a very tall room.",
    "The draft in the tower is the wind applying for residency.",
    // Cats and familiars
    "A cat does not fetch because it has already weighed the cost-benefit analysis.",
    "Cats purr at a frequency that heals bones and soothes existential dread.",
    "A cat sitting on your work is not an obstacle. It is a priority correction.",
    "The cat stares at the wall because it sees things you have agreed to ignore.",
    "Every cat is a philosopher. The good ones are also napping.",
    "A familiar chooses you the way gravity chooses down.",
    "Cats invented meditation, but they never published the paper.",
    "The cat's indifference is an act. The act is flawless.",
    "A sleeping cat is the physical manifestation of inner peace.",
    "Cats knock things off tables to remind you that nothing is permanent.",
    // Candles and light
    "A flame does not try to be bright. It simply burns.",
    "Candlelight is the oldest form of mood lighting and still undefeated.",
    "Every candle is a tiny protest against the dark.",
    "The warmth of a candle proves that small things can change a room.",
    "A candle asks nothing of you. It only gives until it can't.",
    "Wax drips are just candle tears of joy.",
    "To light a candle is to have a conversation with fire.",
    "A wick is just string with a higher calling.",
    "The dance of a flame is choreography without a choreographer.",
    "Candlelight turns every face into a painting.",
    // Sounds and silence
    "Silence is not the absence of sound. It is sound's day off.",
    "Music is just math that learned to dance.",
    "A bell rings once and the sound travels forever, growing quieter but never truly gone.",
    "Humming is just singing that hasn't committed.",
    "Whispers carry further than shouts because secrets are lighter than opinions.",
    "The creak of a floorboard is just the house remembering you.",
    "Rain on a window is the sky tapping out a message in code.",
    "A lullaby is just a spell that works on children.",
    "Rhythm is just time agreeing to be interesting.",
    "The silence after a question is louder than any answer.",
    // Books and knowledge
    "A book is just a mind that can be held in your hands.",
    "Libraries are just graveyards for living thoughts.",
    "Every bookshelf is a timeline of someone's curiosity.",
    "A footnote is just a thought that couldn't help itself.",
    "An index is just a book's way of admitting it's hard to navigate.",
    "Ink is just a liquid that learned to hold still and mean something.",
    "The blank page is not empty. It is full of potential and mild anxiety.",
    "Bookmarks are just a way of telling a book you'll be right back.",
    "A sequel is just a story that didn't know when to stop.",
    "Marginalia is just a reader arguing with a ghost.",
    // Dreams and sleep
    "Dreams are just your brain's screensaver.",
    "Sleep is just death's free trial.",
    "A nightmare is just a dream with poor reviews.",
    "Insomnia is just your brain refusing to close its tabs.",
    "Sleepwalking is just your body going on without you.",
    "A recurring dream is just your subconscious hitting replay.",
    "The snooze button is humanity's greatest act of defiance.",
    "Yawning is just your soul trying to escape and then changing its mind.",
    "Counting sheep is just math in disguise, which is why it doesn't work.",
    "A nap is just a practice run for bedtime.",
];

pub fn check_truth_generation(
    mut wisdom: ResMut<WisdomMeter>,
    mut truth_messages: MessageWriter<TruthGenerated>,
    tracker: Res<PurchaseTracker>,
    school: Res<SchoolState>,
) {
    if wisdom.current >= wisdom.max_wisdom {
        wisdom.current = 0.0;
        wisdom.truths_generated += 1;

        let index = (wisdom.truths_generated as usize - 1) % DEEP_TRUTHS.len();
        truth_messages.write(TruthGenerated {
            text: DEEP_TRUTHS[index].to_string(),
        });

        let scaling = school.scaling_override().unwrap_or(tracker.scaling_factor);
        wisdom.max_wisdom *= scaling;
    }
}
